package Skyflow

import Skyflow.core.Messages

enum class SkyflowErrorCode(val code:Int, var message:String) {

    INVALID_VAULT_ID(400, Messages.INVALID_VAULT_ID.message),
    INVALID_VAULT_URL(400,Messages.INVALID_VAULT_URL.message),
    EMPTY_VAULT_ID(400,Messages.EMPTY_VAULT_ID.message),
    EMPTY_VAULT_URL(400,Messages.EMPTY_VAULT_URL.message),
    INVALID_BEARER_TOKEN(400,Messages.INVALID_BEARER_TOKEN.message),
    BEARER_TOKEN_REJECTED(400,Messages.BEARER_TOKEN_REJECTED.message),
    INVALID_TABLE_NAME(400,Messages.INVALID_TABLE_NAME.message),
    ELEMENT_EMPTY_TABLE_NAME(400,Messages.ELEMENT_EMPTY_TABLE_NAME.message),
    EMPTY_TABLE_KEY(400, Messages.EMPTY_TABLE_KEY.message),
    EMPTY_COLUMN_KEY(400,Messages.EMPTY_COLUMN_KEY.message),
    RECORDS_KEY_NOT_FOUND(400,Messages.RECORDS_KEY_NOT_FOUND.message),
    EMPTY_RECORDS(400,Messages.EMPTY_RECORDS.message),
    TABLE_KEY_ERROR(400,Messages.TABLE_KEY_ERROR.message),
    FIELDS_KEY_NOT_FOUND(400,Messages.FIELDS_KEY_NOT_FOUND.message),
    EMPTY_FIELD_IN_FIELDS(400,Messages.EMPTY_FIELD_IN_FIELDS.message),
    INVALID_COLUMN_NAME(400,Messages.INVALID_COLUMN_NAME.message),
    EMPTY_COLUMN_NAME(400,Messages.EMPTY_COLUMN_NAME.message),
    INVALID_TOKEN_ID(400,Messages.INVALID_TOKEN_ID.message),  // response is in success only, getting both successful and unsuccessful records
    EMPTY_TOKEN(400,Messages.EMPTY_TOKEN.message),
    ID_KEY_ERROR(400,Messages.ID_KEY_ERROR.message),
    REDACTION_KEY_NOT_FOUND(400,Messages.REDACTION_KEY_NOT_FOUND.message),
    INVALID_REDACTION_TYPE(400,Messages.INVALID_REDACTION_TYPE.message),
    INVALID_FIELD(400,Messages.INVALID_FIELD.message),
    TOKEN_KEY_NOT_FOUND(400,Messages.TOKEN_KEY_NOT_FOUND.message),
    MISSING_TOKEN_IN_CONNECTION_REQUEST(400, Messages.MISSING_TOKEN_IN_CONNECTION_REQUEST.message),
    IDS_KEY_NOT_FOUND(404,Messages.IDS_KEY_NOT_FOUND.message),
    EMPTY_RECORD_IDS(400,Messages.EMPTY_RECORD_IDS.message),
    MISSING_TABLE_IN_ELEMENT(400,Messages.MISSING_TABLE_IN_ELEMENT.message),
    TABLE_KEY_NOY_FOUND(400, Messages.TABLE_KEY_NOT_FOUND.message),
    INVALID_RECORD_TABLE_VALUE(400,Messages.INVALID_RECORD_TABLE_VALUE.message),
    INVALID_CONNECTION_URL(400,Messages.INVALID_CONNECTION_URL.message),
    EMPTY_CONNECTION_URL(400,Messages.EMPTY_CONNECTION_URL.message),
    INVALID_INPUT(400,Messages.INVALID_INPUT.message),
    REQUIRED_INPUTS_NOT_PROVIDED(400,Messages.REQUIRED_INPUTS_NOT_PROVIDED.message),
    INVALID_EVENT_TYPE(400,Messages.INVALID_EVENT_TYPE.message),
    INVALID_EVENT_LISTENER(400,Messages.INVALID_EVENT_LISTENER.message),
    UNKNOWN_ERROR(400,Messages.UNKNOWN_ERROR.message),
    TRANSACTION_ERROR(400,Messages.TRANSACTION_ERROR.message),
    CONNECTION_ERROR(400,Messages.CONNECTION_ERROR.message),
    EMPTY_REDACTION_VALUE(400,Messages.EMPTY_REDACTION_VALUE.message),
    ELEMENT_NOT_MOUNTED(400,Messages.ELEMENT_NOT_MOUNTED.message),
    DUPLICATE_COLUMN_FOUND(400,Messages.DUPLICATE_COLUMN_FOUND.message),
    DUPLICATE_ELEMENT_FOUND(400,Messages.DUPLICATE_ELEMENT_FOUND.message),
    INVALID_RECORDS(400,Messages.INVALID_RECORDS_TYPE.message),
    INVALID_IDS(400,Messages.INVALID_IDS.message),
    EMPTY_ID_IN_RECORD_IDS(400, Messages.EMPTY_ID_IN_RECORD_IDS.message),
    MISSING_REDACTION(400,Messages.MISSING_REDACTION.message),
    EMPTY_KEY_IN_REQUEST_BODY(400,Messages.EMPTY_KEY_IN_REQUEST_BODY.message),
    EMPTY_KEY_IN_QUERY_PARAMS(400,Messages.EMPTY_KEY_IN_QUERY_PARAMS.message),
    EMPTY_KEY_IN_PATH_PARAMS(400,Messages.EMPTY_KEY_IN_PATH_PARAMS.message),
    EMPTY_KEY_IN_REQUEST_HEADER_PARAMS(400,Messages.EMPTY_KEY_IN_REQUEST_HEADER_PARAMS.message),
    INVALID_FIELD_IN_PATH_PARAMS(400,Messages.INVALID_FIELD_IN_PATH_PARAMS.message),
    INVALID_FIELD_IN_QUERY_PARAMS(400,Messages.INVALID_FIELD_IN_QUERY_PARAMS.message),
    INVALID_FIELD_IN_REQUEST_HEADER_PARAMS(400,Messages.INVALID_FIELD_IN_REQUEST_HEADER_PARAMS.message),
    INVALID_FIELD_IN_REQUEST_BODY(400,Messages.INVALID_FIELD_IN_REQUEST_BODY.message),
    FAILED_TO_REVEAL(400,Messages.FAILED_TO_REVEAL.message),
    NOT_FOUND_IN_RESPONSE(400,Messages.NOT_FOUND_IN_RESPONSE.message),
    BAD_REQUEST(400,Messages.BAD_REQUEST.message),
    MISSING_COLUMN(400,Messages.MISSING_COLUMN.message),
    SERVER_ERROR(500, Messages.SERVER_ERROR.message),
    EMPTY_FIELDS(400,Messages.EMPTY_FIELDS.message),
    INVALID_REQUEST_XML(400,Messages.INVALID_REQUEST_XML.message),
    INVALID_RESPONSE_XML(400,Messages.INVALID_RESPONSE_XML.message),
    INVALID_ID_IN_REQUEST_XML(400,Messages.INVALID_ID_IN_REQUEST_XML.message),
    EMPTY_ID_IN_REQUEST_XML(400,Messages.EMPTY_ID_IN_REQUEST_XML.message),
    INVALID_ID_IN_RESPONSE_XML(400,Messages.INVALID_ID_IN_RESPONSE_XML.message),
    NOT_FOUND_IN_RESPONSE_XML(400,Messages.NOT_FOUND_IN_RESPONSE_XML.message),
    AMBIGUOUS_ELEMENT_FOUND_IN_RESPONSE_XML(400,Messages.AMBIGUOUS_ELEMENT_FOUND_IN_RESPONSE_XML.message),
    EMPTY_ID_IN_RESPONSE_XML(400,Messages.EMPTY_ID_IN_RESPONSE_XML.message),
    DUPLICATE_ID_IN_RESPONSE_XML(400,Messages.DUPLICATE_ID_IN_RESPONSE_XML.message),
    EMPTY_REQUEST_XML(400,Messages.EMPTY_REQUEST_XML.message),
    INVALID_FORMAT_REGEX(400,Messages.INVALID_FORMAT_REGEX.message),
    NOT_VALID_TOKENS(400,Messages.NOT_VALID_TOKENS.message),
    NO_TABLE_KEY_IN_UPSERT(400,Messages.NO_TABLE_KEY_IN_UPSERT.message),
    NO_COLUMN_KEY_IN_UPSERT(400,Messages.NO_COLUMN_KEY_IN_UPSERT.message),
    INVALID_TABLE_IN_UPSERT_OPTION(400,Messages.INVALID_TABLE_IN_UPSERT_OPTION.message),
    INVALID_COLUMN_IN_UPSERT_OPTION(400,Messages.INVALID_COLUMN_IN_UPSERT_OPTION.message),
    ALLOW_JSON_OBJECT_IN_UPSERT(400,Messages.ALLOW_JSON_OBJECT_IN_UPSERT.message),
    EMPTY_UPSERT_OPTIONS_ARRAY(400,Messages.EMPTY_UPSERT_OPTIONS_ARRAY.message),
    EMPTY_RECORD_OBJECT(400, Messages.EMPTY_RECORD_OBJECT.message),
    EMPTY_RECORD_IDS_IN_GET(400, Messages.EMPTY_RECORD_IDS_IN_GET.message),
    INVALID_ID_IN_RECORD_IDS(400, Messages.INVALID_ID_IN_RECORD_IDS.message),
    REDACTION_WITH_TOKENS_NOT_SUPPORTED(400, Messages.REDACTION_WITH_TOKENS_NOT_SUPPORTED.message),
    TOKENS_NOT_SUPPORTED_WITH_COLUMN_DETAILS(
        400,
        Messages.TOKENS_NOT_SUPPORTED_WITH_COLUMN_DETAILS.message
    ),
    MISSING_RECORD_COLUMN_VALUES(400, Messages.RECORD_COLUMN_VALUES_NOT_FOUND.message),
    MISSING_RECORD_COLUMN_NAME(400, Messages.RECORD_COLUMN_NAME_NOT_FOUND.message),
    INVALID_RECORD_COLUMN_NAME_TYPE(400,Messages.INVALID_RECORD_COLUMN_NAME_TYPE.message),
    EMPTY_RECORD_COLUMN_NAME(400, Messages.EMPTY_RECORD_COLUMN_NAME.message),
    INVALID_RECORD_COLUMN_VALUES_TYPE(400, Messages.INVALID_RECORD_COLUMN_VALUES_TYPE.message),
    INVALID_COLUMN_VALUE_TYPE(400, Messages.INVALID_COLUMN_VALUE_TYPE.message),
    EMPTY_RECORD_COLUMN_VALUES(400, Messages.EMPTY_RECORD_COLUMN_VALUES.message),
    EMPTY_COLUMN_VALUE(400, Messages.EMPTY_COLUMN_VALUE.message),
    BOTH_IDS_AND_COLUMN_DETAILS_SPECIFIED(
        400,
        Messages.BOTH_IDS_AND_COLUMN_DETAILS_SPECIFIED.message
    ),
    NEITHER_IDS_NOR_COLUMN_DETAILS_SPECIFIED(
        400, Messages.NEITHER_IDS_NOR_COLUMN_DETAILS_SPECIFIED.message
    ),
    FAILED_TO_GET(400,Messages.FAILED_TO_GET.message),
    MISMATCH_ELEMENT_COUNT_LAYOUT_SUM(400, Messages.MISMATCH_ELEMENT_COUNT_LAYOUT_SUM.message),

    TOKEN_KEY_NOT_FOUND_REVEAL(400, Messages.TOKEN_KEY_NOT_FOUND_REVEAL.message),
    EMPTY_TOKEN_REVEAL(400, Messages.EMPTY_TOKEN_REVEAL.message),
    ELEMENT_NOT_MOUNTED_REVEAL(400, Messages.ELEMENT_NOT_MOUNTED_REVEAL.message),
    ERROR_STATE_REVEAL(400, Messages.ERROR_STATE_REVEAL.message),

    ADDITIONAL_FIELDS_RECORDS_KEY_NOT_FOUND(400, Messages.ADDITIONAL_FIELDS_RECORDS_KEY_NOT_FOUND.message),
    ADDITIONAL_FIELDS_INVALID_RECORDS(400,Messages.ADDITIONAL_FIELDS_INVALID_RECORDS_TYPE.message),
    ADDITIONAL_FIELDS_EMPTY_RECORDS(400, Messages.ADDITIONAL_FIELDS_EMPTY_RECORDS.message),
    ADDITIONAL_FIELDS_TABLE_KEY_NOT_FOUND(400, Messages.ADDITIONAL_FIELDS_TABLE_KEY_NOT_FOUND.message),
    ADDITIONAL_FIELDS_EMPTY_TABLE_KEY(400, Messages.ADDITIONAL_FIELDS_EMPTY_TABLE_KEY.message),
    ADDITIONAL_FIELDS_INVALID_TABLE_NAME(400, Messages.ADDITIONAL_FIELDS_INVALID_TABLE_NAME.message),
    ADDITIONAL_FIELDS_FIELDS_KEY_NOT_FOUND(400, Messages.ADDITIONAL_FIELDS_FIELDS_KEY_NOT_FOUND.message),
    ADDITIONAL_FIELDS_EMPTY_FIELDS(400, Messages.ADDITIONAL_FIELDS_EMPTY_FIELDS.message),

    EMPTY_TOKEN_ID(400, Messages.EMPTY_TOKEN_ID.message),
    MISSING_TOKEN(400, Messages.MISSING_TOKEN.message)
    ;

    @JvmName("getCode1")
    fun getCode() : Int {
        return this.code
    }

    @JvmName("getMessage1")
    fun getMessage() : String {
        return this.message
    }
}